(deftheme home-dark
  "Customized dark theme")

(custom-theme-set-faces
 'home-dark
 '(font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
 '(font-lock-constant-face ((t (:foreground "LightSlateBlue"))))
 '(font-lock-preprocessor-face ((t (:foreground "CornFlowerBlue"))))
 '(font-lock-keyword-face ((t (:foreground "cyan1"))))
 '(font-lock-type-face ((t (:foreground "SteelBlue1"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "Aquamarine"))))
 '(font-lock-function-name-face ((t (:foreground "mediumspringgreen" :weight bold :height 1.1))))
 '(font-lock-string-face ((t (:foreground "RosyBrown1"))))
 '(font-lock-comment-face ((t (:slant oblique :foreground "chocolate1"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "Salmon"))))
 '(font-lock-doc-face ((t (:slant oblique :foreground "LightCoral"))))
 '(font-lock-doc-string-face ((t (:foreground "Plum"))))
 '(font-lock-warning-face ((t (:foreground "Pink" :weight bold))))
 '(Info-title-1-face ((t (:weight bold :family "helv" :height 1.728))))
 '(Info-title-2-face ((t (:family "helv" :weight bold :height 1.44))))
 '(Info-title-3-face ((t (:weight bold :family "helv" :height 1.2))))
 '(Info-title-4-face ((t (:family "helv" :weight bold))))
 '(bold ((t (:weight bold))))
 '(bold-italic ((t (:slant italic :weight bold))))
 '(buffer-menu-buffer ((t (:weight bold))))
 '(comint-highlight-input ((t (:weight bold))))
 '(comint-highlight-prompt ((t (:foreground "cyan1"))))
 '(compilation-column-number ((t (:foreground "PaleGreen"))))
 '(compilation-error ((t (:weight bold :foreground "Brown1"))))
 '(compilation-info ((t (:foreground "LightPink1" :weight bold))))
 '(compilation-line-number ((t (:foreground "LightGoldenrod"))))
 '(compilation-message-face ((t (:underline t))))
 '(compilation-warning ((t (:foreground "Orange" :weight bold))))
 '(compilation-warning-face ((t (:foreground "Orange" :weight bold))))
 '(completions-common-part ((t (:family "unknown-DejaVu Sans Mono" :width normal :weight normal :slant normal :foreground "WhiteSmoke" :background "black" :height 81))))
 '(completions-first-difference ((t (:weight bold))))
 '(css-selector ((t (:foreground "LightSteelBlue"))))
 '(css-property ((t (:foreground "light sea green"))))
 '(diff-file-header ((t (:background "grey20" :foreground "ivory1" :weight bold))))
 '(diff-hunk-header ((t (:slant italic :background "DodgerBlue4"))))
 '(diff-nonexistent ((t (:weight bold :background "Black" :foreground "Wheat1"))))
 '(diff-refine-change ((t (:background "MidnightBlue"))))
 '(ediff-current-diff-A ((((class color)) (:background "sea green" :foreground "black"))))
 '(ediff-current-diff-Ancestor ((((class color)) (:background "sea green" :foreground "black"))))
 '(ediff-current-diff-B ((((class color)) (:background "sea green" :foreground "black"))))
 '(ediff-current-diff-C ((((class color)) (:background "sea green" :foreground "black"))))
 '(ediff-even-diff-A ((((class color)) (:background "cyan" :foreground "black"))))
 '(ediff-even-diff-Ancestor ((((class color)) (:background "cyan" :foreground "black"))))
 '(ediff-even-diff-B ((((class color)) (:background "cyan" :foreground "black"))))
 '(ediff-even-diff-C ((((class color)) (:background "cyan" :foreground "black"))))
 '(ediff-fine-diff-A ((((class color)) (:background "magenta" :foreground "black"))))
 '(ediff-fine-diff-Ancestor ((((class color)) (:background "magenta" :foreground "black"))))
 '(ediff-fine-diff-B ((((class color)) (:background "magenta" :foreground "black"))))
 '(ediff-fine-diff-C ((((class color)) (:background "magenta" :foreground "black"))))
 '(ediff-odd-diff-A ((((class color)) (:background "cyan" :foreground "black"))))
 '(ediff-odd-diff-Ancestor ((((class color)) (:background "cyan" :foreground "black"))))
 '(ediff-odd-diff-B ((((class color)) (:background "cyan" :foreground "black"))))
 '(ediff-odd-diff-C ((((class color)) (:background "cyan" :foreground "black"))))
 '(fixed-pitch ((t (:family "courier"))))
 '(help-argument-name ((t (:slant italic))))
 '(highlight ((t (:background "gray10" :foreground "Old Lace"))))
 '(hl-line ((t (:background "grey10" :foreground "Old Lace"))))
 '(align-highlight-change-face ((t (:background "darkseagreen2" :foreground "blue"))))
 '(ispell-highlight-face ((t (:background "darkseagreen2" :foreground "blue"))))
 '(widget-mouse-face ((t (:background "darkseagreen2" :foreground "blue"))))
 '(info-menu-5 ((t (:underline t))))
 '(info-menu-header ((t (:family "helv" :weight bold))))
 '(info-node ((t (:foreground "white" :slant italic :weight bold))))
 '(info-xref ((t (:foreground "cyan" :weight bold))))
 '(isearch ((t (:background "palevioletred2" :foreground "brown4"))))
 '(isearch-fail ((t (:background "red4"))))
 '(isearch-secondary ((t (:foreground "red3"))))
 '(italic ((t nil)))
 '(lazy-highlight ((t (:background "paleturquoise4"))))
 '(link ((t (:foreground "cyan1" :underline t))))
 '(link-visited ((t (:underline t :foreground "violet"))))
 '(makefile-space ((t (:background "hotpink"))))
 '(man-bold ((t nil)))
 '(man-heading ((t nil)))
 '(man-italic ((t (:foreground "yellow"))))
 '(man-xref ((t (:underline t))))
 '(match ((t (:background "RoyalBlue3"))))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(mode-line ((t (:height 0.9 :box nil :foreground "snow" :background "midnightblue" :inverse-video nil))))
 '(mode-line-buffer-id ((t (:foreground "yellow"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:color "grey40")))))
 '(mode-line-inactive ((t (:inherit default :background "grey30" :foreground "grey80" :box (:color "grey40") :weight light :height 0.9))))
 '(next-error ((t (:background "blue3"))))
 '(paren-blink-off ((t (:foreground "black"))))
 '(paren-mismatch-face ((t (:background "white" :foreground "red"))))
 '(paren-no-match-face ((t (:background "white" :foreground "red"))))
 '(query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
 '(region ((t (:background "blue3"))))
 '(scroll-bar ((t (:background "grey75" :foreground "WhiteSmoke"))))
 '(secondary-selection ((t (:background "SkyBlue4"))))
 '(shadow ((t (:foreground "grey70"))))
 '(show-paren-match ((t (:background "steelblue3"))))
 '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
 '(trailing-whitespace ((t (:background "red1"))))
 '(underline ((t (:underline t))))
 '(variable-pitch ((t (:family "helv"))))
 '(vcursor ((t (:foreground "blue" :background "cyan" :underline t))))
 '(vertical-border ((t (:background "dim gray"))))
 '(which-func ((t (:foreground "Blue1"))))
 '(default ((t (:background "black" :foreground "WhiteSmoke"))))
 '(ediff-current-diff-Ancestor ((((class color)) (:background "sea green" :foreground "black"))))
)

(provide-theme 'home-dark)
